alpha: 2.5
batch_size: 256
buffer_size: 10000000
checkpoints_path: checkpoints/TD3-BC
device: cuda
discount: 0.99
env: H1JoystickGaitTracking
dataset_id: playground/H1JoystickGaitTracking-foward-expert-v1
eval_freq: 5000
expl_noise: 0.1 
group: td3-bc-h1-expert-v1
load_model: ''
max_timesteps: 1000000
n_episodes: 10
name: TD3-BC
noise_clip: 0.5
normalize: false
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
project: Offline-Benchmark
seed: 0
tau: 0.005
command_type: foward