awac_lambda: 0.1
batch_size: 256
buffer_size: 10000000
checkpoints_path: checkpoints/AWAC
device: cuda
env: H1JoystickGaitTracking
dataset_id: playground/H1JoystickGaitTracking-direction-medium-v1
eval_frequency: 1000
gamma: 0.99
group: awac-h1-joystick-flat-medium-v1
hidden_dim: 256
learning_rate: 0.0003
n_test_episodes: 10
num_train_ops: 1000000
project: Offline-Benchmark
seed: 42
tau: 0.005
test_seed: 69
command_type: direction
