actor_lr: 3e-4
batch_size: 256
beta: 3.0
buffer_size: 10000000
checkpoints_path: checkpoints/IQL
device: cuda
discount: 0.99
env: G1JoystickFlatTerrain
dataset_id: playground/G1JoystickFlatTerrain-foward-expert-v1
eval_freq: 5000
group: iql-g1-joystick-flat-expert-v1
iql_deterministic: false
iql_tau: 0.7
load_model: ''
max_timesteps: 1000000
n_episodes: 10
name: IQL
normalize: true
normalize_reward: false
qf_lr: 3e-4
project: Offline-Benchmark
seed: 0
tau: 0.005
vf_lr: 3e-4
command_type: foward